[package]
name = "device-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
dirs.workspace = true
inquire.workspace = true
serde.workspace = true
toml.workspace = true
