[general]
# The module to run when no prefix is matched
default_module = "gg"
# The module to run with an empty prompt
empty_module = ""
# Your shell or window manager, default to sh
# for example: "swaymsg exec" for swaywm; "hyprctl dispatch exec" for hyprland; "zsh -c" for zsh
exec_cmd = "hyprctl dispatch exec"
# Fuzzy search for prefixes; autocompletion with TAB
show_suggestion = true


[interface]
# Ascii color codes are allowed. However, \x1b[ should be replaced with \u001B[ (unicode escape) because the rust toml crate cannot read \x as an escaped character...
header_cmd = "" # Run a shell command with its output printed as the header
header_cmd_trimmed_lines = 0 # Remove a number of lines from header_cmd output, in case of excessive empty lines printed at the end
header = ""
prompt_prefix = " \u001B[34m \u001B[0m otter-launcher \u001B[34m>>\u001B[0m"
list_prefix = "  \u001B[34m>>\u001B[0m"
highlighted_prefix = "  \u001B[34m#>\u001B[0m"
scroll_up_prefix = "  \u001B[34m#!\u001B[0m"
scroll_down_prefix = "  \u001B[34m#!\u001B[0m"
help_message = ""
place_holder = "type and search..."
suggestion_lines = 1


# Modules are defined as below. Desc, prefix, and cmd are essential and must be specified; others are optional.
[[modules]]
description = "search with google"
prefix = "\u001B[32mgg\u001B[0m"
cmd = "xdg-open 'https://www.google.com/search?q={}'"
# If "with_argument" is true, the {} in the cmd value will be replaced with user input. If the field is not explicitly set, will be taken as false.
with_argument = true
# "url_encode" should be true if the module is set to call webpages, as this ensures special characters in url being readable to browsers. It'd better be false with shell scripts. If the field is not explicitly set, will be taken as false.
url_encode = true

[[modules]]
description = "open files with fzf"
prefix = "\u001B[32mfo\u001B[0m"
cmd = "$TERM --class fzf -e sh -c 'fd --type f | fzf | xargs xdg-open'"
# if set, the prehook command will run before the main cmd starts.
prehook = "swaymsg '[app_id=fzf] floating on; [app_id=fzf] resize set width 600 px height 300 px'"
# if set, the callback command will run after the main cmd has finished.
callback = ""

[[modules]]
description = "search for directories with yazi"
prefix = "\u001B[32myz\u001B[0m"
cmd = "$TERM --class yazi -e sh -c 'fd --type d | fzf | xargs $TERM -e yazi'"

[[modules]]
description = "cambridge dictionary online"
prefix = "\u001B[32mdc\u001B[0m"
cmd = "xdg-open 'https://dictionary.cambridge.org/dictionary/english/{}'"
with_argument = true
url_encode = true
