[package]
name = "cams-home-utilities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
rand.workspace = true
# catppuccinifier-rs.workspace = true
